### ISSUE TITLE
mipgap parameter 5e-2 may be too large 

### ISSUE THREAD

**Issue by monodera** [Subaru-PFS/spt_target_uploader#182]
I got a comment from Evan Kirby saying that the `mipgap` parameter used in the uploader PPP (5e-2) is too large and he recommend to test lower numbers such as 5e-4. What do you think?

**Comment by kiyoyabe** [comment]
The default value that Gurobi recommends is 1e-4, so worth testing 5e-4, but it should increase computation time.
https://www.gurobi.com/documentation/current/refman/mipgap2.html#parameter:MIPGap

**Comment by monodera** [comment]
Perhaps @mihoishigaki can describe the issue in detail, but Evan said that with `mipgap=5e-2`, only 400 science targets out of a lot many. We can ask him to share his target list and see how the results changes by changing `mipgap`. I understand that lowering the parameter would increase the computational time, but there may be a nice parameter space to balance the degree of optimization and computational time.

**Comment by wanqqq31** [comment]
I have noticed this issue long ago. My feeling is that online PPP does not provide very accurate fiber assignment, but only a statistic view (we emphasize this in manual page already). And I expect the results should be worse than the optimized results, leaving some space for bad weather, etc. For this point of view, I think it is ok to keep a higher tolerance to save running time (especially online PPP is expected to be executed by many users simultaneously). 

With a lower tolerance, it would take much longer time, and I do not think 15min is enough for reaching that tolerance with a dense compact sample for ~100-200 pointings. FYI, in the e2e simulation, ~30,000 targets (targets in the low-res mode; several separate regions with different densities) with 180 pointings already takes ~10min to get netflow results with mipgap=5e-2. If you prefer a smaller tolerance, the possible way may be running netflow for each pointing separately, instead of for all the pointings simultaneously. But again, the result remains worse than the optimized one. --> we might need to check which one gets closer to the optimized result.

**Comment by mihoishigaki** [comment]
Thanks Onodera-san, Yabe-san and He-san for your comments. The target list Evan mentioned is attached here. With the online PPP, 1572 objects (fiber hour= 393, used fiber fraction = 66%) got fibers for the first pointing. On the other hand, Evan's netflow run resulted in >2000 objects getting fibers. Can this difference explained by the difference in mipgap alone? Or do any other settings in the code contribute? Here is what Evan used for the gurobi parameter:
  gurobiOptions = dict(seed=0, presolve=1, method=4, degenmoves=0,
                            heuristics=0.5, mipfocus=3, mipgap=5.0e-04, LogToConsole=1, timelimit = 15500.0)
         
[ursaminor_netflow.csv](https://github.com/monodera/pfs_target_uploader/files/14580396/ursaminor_netflow.csv)

**Comment by wanqqq31** [comment]
I will check the fiber assignment of the sample with different tolerance. Thanks for sharing the list.

**Comment by mihoishigaki** [comment]
As for my comment above https://github.com/monodera/pfs_target_uploader/issues/182#issuecomment-1992893233

Evan's netflow result includes science targets, sky (240 fibers), and flux standards (50 fibers). If we only include science targets, the resulting fiber usage fraction is similar (~60%) to the online PPP result. 

By changing mipgap ; 

mipgap=5e-2 -> mipgap=5e-4, the improvement in fiber usage: <1% 
mipgap=5e-4 -> mipgap=1e-4, the improvement in fiber usage: ~8% 

for the target list above and a specific set of "classdict" (nonObservationCost, etc.). 

Therefore, the difference between the GA group's fiber assignment and that of the online PPP is not due to an issue in online PPP. Sorry about my misunderstanding. 

The mipgap difference does not contribute much, although there was an improvement by setting mipgap=1e-4 (the default value mentioned by Yabe-san).

**Comment by monodera** [comment]
Thanks for the report. Is it still strange that the number of science objects with fiber assignments gets smaller because 300 fibers are about 12% of the total fibers?

**Comment by mihoishigaki** [comment]
The original GA target list contains random Gaia stars, so those objects filled up the remaining fibers. I will continue to look at other GA fields with various target densities.
